from youtubeopinion.extraction.text import get_sentence_polarity, generate_polarity_for_sentences
from youtubeopinion.extraction.audio import get_audio_from_video
from youtubeopinion.extraction.video import get_video_from_youtube